# Generated by Django 4.2.4 on 2023-10-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_report',
        ),
        migrations.RemoveField(
            model_name='game',
            name='needs_admin',
        ),
        migrations.AddField(
            model_name='assignment',
            name='game_report',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='needs_admin',
            field=models.BooleanField(null=True),
        ),
    ]
