# Generated by Django 4.2.4 on 2023-09-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accessCode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
